// web3-frontend/src/components/Hero.tsx
function Hero() {

    return (
        <div className="hero min-h-screen" style={{ backgroundImage: 'url(https://cdn.leonardo.ai/users/24818790-262a-4ae6-b0ae-093cf8cdd4d4/generations/aa072854-a672-43af-bde3-16a3154e2472/Leonardo_Diffusion_XL_Step_into_a_world_of_sweet_possibilities_2.jpg)' }}>
            <div className="hero-overlay bg-opacity-60"></div>
            <div className="hero-content text-center text-neutral-content">
                <div className="max-w-md">
                    <h1 className="mb-5 text-5xl font-bold">Indulge in Sweetness, Pay with Crypto</h1>
                </div>
            </div>
        </div>
    )
}

export default Hero;

// web3-frontend-svelte/src/lib/components/Hero.svelte
<script>

</script>

<div class="hero min-h-screen" style="background-image: url('https://cdn.leonardo.ai/users/24818790-262a-4ae6-b0ae-093cf8cdd4d4/generations/aa072854-a672-43af-bde3-16a3154e2472/Leonardo_Diffusion_XL_Step_into_a_world_of_sweet_possibilities_2.jpg')">
    <div class="hero-overlay bg-opacity-60"></div>
    <div class="hero-content text-center text-neutral-content">
        <div class="max-w-md">
            <h1 class="mb-5 text-5xl font-bold">Indulge in Sweetness, Pay with Crypto</h1>
        </div>
    </div>
</div>
