// web3-frontend/src/components/Navbar.tsx
function Navbar() {

    return (
        <div className="navbar bg-secondary">
            <div className="flex-1">
                <a className="btn btn-ghost text-base-100 normal-case text-xl">Cryptandy</a>
            </div>
            <div className="flex-none navbar-end">
                <a className="btn btn-accent normal-case text-xl text-base-100">Connect</a>
            </div>
        </div>
    )
}

export default Navbar;

// web3-frontend-svelte/src/lib/components/Navbar.svelte
<script>
    import ConnectWalletButton from "./ConnectWalletButton.svelte";
</script>

<div class="navbar bg-secondary">
    <div class="flex-1">
        <a href="#top" class="btn btn-ghost text-base-100 normal-case text-xl">Cryptandy</a>
    </div>
    <div class="flex-none navbar-end">
        <ConnectWalletButton/>
    </div>
</div>
